---
abstract: 'Simple serialization format'
author:
  - 'Mark Lawrencde <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
  Test::Needs: '0'
  Text::Diff: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.08'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bifcode-V2
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter::Tidy: '0'
  boolean: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  repository: https://github.com/mlawren/p5-Bifcode
version: 2.000_2
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
